# Generated by Django 4.2.7 on 2023-12-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=20)),
                ('building_number', models.CharField(max_length=3)),
                ('apartment_number', models.CharField(max_length=3)),
                ('metres', models.DecimalField(decimal_places=3, max_digits=3)),
                ('client_price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('enter', models.CharField(choices=[('H', 'I will be at home'), ('O', 'Other option'), ('K', 'I will give a key')], default='H', max_length=1)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.package')),
            ],
        ),
    ]
