# Generated by Django 4.2.7 on 2023-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_number',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('K', 'I will give a key'), ('O', 'Other option'), ('H', 'I will be at home')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='metres',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_price',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
