# Generated by Django 4.2.7 on 2023-12-14 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0009_alter_order_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('O', 'Other option'), ('K', 'I will give a key'), ('H', 'I will be at home')], default='H', max_length=1),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('comment', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.order')),
            ],
        ),
    ]
