# Generated by Django 4.2.7 on 2023-12-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_order_enter_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('H', 'I will be at home'), ('K', 'I will give a key'), ('O', 'Other option')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_proposals', to='client.proposal'),
        ),
    ]
