# Generated by Django 4.2.7 on 2023-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_order_enter_alter_order_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposals',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
