# Generated by Django 4.2.7 on 2023-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_order_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('H', 'I will be at home'), ('O', 'Other option'), ('K', 'I will give a key')], default='H', max_length=1),
        ),
    ]
