# Generated by Django 4.2.7 on 2023-12-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_order_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('K', 'I will give a key'), ('H', 'I will be at home'), ('O', 'Other option')], default='H', max_length=1),
        ),
    ]
