# Generated by Django 4.2.7 on 2023-12-15 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_order_proposals_list_alter_order_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('K', 'I will give a key'), ('H', 'I will be at home'), ('O', 'Other option')], default='H', max_length=1),
        ),
    ]
