# Generated by Django 4.2.7 on 2023-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_order_taken_by_alter_order_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done_cleaner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('O', 'Other option'), ('K', 'I will give a key'), ('H', 'I will be at home')], default='H', max_length=1),
        ),
    ]
