# Generated by Django 4.2.7 on 2023-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_review_profile_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('K', 'I will give a key'), ('H', 'I will be at home'), ('O', 'Other option')], default='H', max_length=1),
        ),
    ]
