# Generated by Django 4.2.7 on 2023-12-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_review_communication_rating_alter_order_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('H', 'I will be at home'), ('O', 'Other option'), ('K', 'I will give a key')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
