# Generated by Django 5.0.1 on 2024-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_order_accepted_alter_order_enter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_price',
            new_name='client_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('K', 'I will give a key'), ('O', 'Other option'), ('H', 'I will be at home')], default='H', max_length=1),
        ),
    ]
