# Generated by Django 5.0.1 on 2024-01-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_rename_your_price_order_client_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(choices=[('H', 'I will be at home'), ('K', 'I will give a key'), ('O', 'Other option')], default='H', max_length=1),
        ),
    ]
